# Generated by Django 6.1.1 on 2026-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_analysis_enabled',
            field=models.BooleanField(default=True, verbose_name='permitir análise com IA'),
        ),
    ]
