# Generated by Django 6.1.1 on 2026-09-25 10:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='banco/instituição')),
                ('account_type', models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('wallet', 'Carteira'), ('investment', 'Investimento'), ('other', 'Outro')], default='checking', max_length=20, verbose_name='tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
            },
        ),
    ]
