# Generated by Django 6.1.1 on 2026-09-29 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField(verbose_name='mês de referência')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Gerando'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('insufficient_data', 'Dados insuficientes')], default='pending', max_length=20, verbose_name='situação')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='conteúdo')),
                ('schema_version', models.PositiveSmallIntegerField(default=1, verbose_name='versão do schema')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de entrada')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens de saída')),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='total de tokens')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_analyses', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'análise mensal',
                'verbose_name_plural': 'análises mensais',
                'ordering': ['-reference_month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reference_month'), name='unique_analysis_per_user_month'), models.CheckConstraint(condition=models.Q(('reference_month__day', 1)), name='analysis_reference_month_first_day')],
            },
        ),
    ]
